/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examensuple;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Tabla Articulos");
        mostrarTabla();
    }

    Controlador con = new Controlador();
    Connection cone = con.conexion();
    Connection conex = con.crearTablaArticulos();
    ArrayList<Articulos> articulos = new ArrayList<Articulos>();

    int indiceActual, totalResultados = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtClaveproducto = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtClaveFabricante = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaArt = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtSiguiente = new javax.swing.JTextField();
        txtAnterior = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNombrefabricante = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnDescuentp = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Clave Producto");

        jLabel2.setText("Nombre");

        jLabel3.setText("Precio");

        jLabel4.setText("Clave fabricante");

        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        TablaArt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaArt);

        jButton1.setText("Anterior");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Siguiente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ram Y Usb");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("100-350");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Nombre fabricante");

        txtNombrefabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrefabricanteActionPerformed(evt);
            }
        });

        jLabel5.setText("Pregunta 2 ");

        jLabel6.setText("Pregunta 3 ");

        btnDescuentp.setText("mayor 450");
        btnDescuentp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescuentpActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel8.setText("Pregunta 4");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("TIENDA");

        jButton5.setText("Precio y Prod");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel10.setText("Pregunta 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)
                                .addGap(21, 21, 21)
                                .addComponent(btnDescuentp))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtClaveproducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                        .addComponent(txtNombre)
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtClaveFabricante, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(txtNombrefabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(btnAñadir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar)))
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(txtSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtClaveproducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtClaveFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtNombrefabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAñadir)
                            .addComponent(btnLimpiar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDescuentp)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed

        String claveArticulo = txtClaveproducto.getText();
        String nombre = txtNombre.getText();
        int precio = Integer.parseInt(txtPrecio.getText());
        String claveFabricante = txtClaveFabricante.getText();
        String nombreFabricante = txtNombrefabricante.getText();

        try {
            String insertar = " Insert into Articulos (claveArticulo,nombre,precio,claveFabricante,nombreFabricante) values (?,?,?,?,?)";

            PreparedStatement pstm = cone.prepareStatement(insertar);
            pstm.setString(1, claveArticulo);
            pstm.setString(2, nombre);
            pstm.setInt(3, precio);
            pstm.setString(4, claveFabricante);
            pstm.setString(5, nombreFabricante);

            pstm.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos ingresados correctamente");

            mostrarTabla();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error" + e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int cont = indiceActual + 1;
        totalResultados = articulos.size();

        if (cont < totalResultados) {
            Articulos a = articulos.get(cont);
            setTextos(a, cont, totalResultados);
            indiceActual++;

        } else {
            JOptionPane.showMessageDialog(null, "Fin d la lista");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int cont = indiceActual - 1;

        if (cont >= 0) {
            Articulos a = articulos.get(cont);
            setTextos(a, cont, totalResultados);
            indiceActual--;

        } else {
            System.out.println("Fin de lista");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        getArticulos();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        getArticulosPrecio();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtNombrefabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrefabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrefabricanteActionPerformed

    private void btnDescuentpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescuentpActionPerformed
        getArticulosPreciocambiado();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDescuentpActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtAnterior.setText("");
        txtClaveFabricante.setText("");
        txtClaveproducto.setText("");
        txtNombre.setText("");
        txtNombrefabricante.setText("");
        txtPrecio.setText("");
        txtSiguiente.setText("");
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
getArticulosnombresPrecios();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    void mostrarTabla() {

        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Clave Articulo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Clave Fabricante");
        modelo.addColumn("Nombre Fabricante");

        TablaArt.setModel(modelo);

        String sql = "Select * from Articulos";
        String datos[] = new String[5];

        try {
            Statement stm = cone.createStatement();
            ResultSet resultado = stm.executeQuery(sql);
            while (resultado.next()) {
                datos[0] = resultado.getString(1);
                datos[1] = resultado.getString(2);
                datos[2] = resultado.getString(3);
                datos[3] = resultado.getString(4);
                datos[4] = resultado.getString(5);

                modelo.addRow(datos);
            }
            TablaArt.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e);
        }
    }

    public ArrayList getArticulos() {

        try {

            String sql = "select * from Articulos where nombre = 'memoria ram' or nombre = 'memoria usb'";

            PreparedStatement pstm = cone.prepareStatement(sql);
            ResultSet resultados = pstm.executeQuery();

            while (resultados.next()) {
                String claveProducto = resultados.getString("claveArticulo");
                String nombre = resultados.getString("Nombre");
                int precio = resultados.getInt("precio");
                String claveFabricante = resultados.getString("claveFabricante");
                String nombrefabricante = resultados.getString("nombreFabricante");

                Articulos articulo = new Articulos(claveProducto, nombre, precio, claveFabricante, nombrefabricante);

                articulos.add(articulo);
            }

            Articulos art = articulos.get(indiceActual);
            setTextos(art, indiceActual, totalResultados);
            mostrarTabla();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e);

        }

        return articulos;
    }

    public ArrayList getArticulosPrecio() {

        try {

            String sql = "select * from Articulos where precio >= 100 and precio <= 350";

            PreparedStatement pstm = cone.prepareStatement(sql);
            ResultSet resultados = pstm.executeQuery();

            while (resultados.next()) {
                String claveArticulo = resultados.getString("claveArticulo");
                String nombre = resultados.getString("Nombre");
                int precio = resultados.getInt("precio");
                String claveFabricante = resultados.getString("claveFabricante");
                String nombreFabricante = resultados.getString("nombreFabricante");

                Articulos articulo = new Articulos(claveArticulo, nombre, precio, claveFabricante, nombreFabricante);

                articulos.add(articulo);
            }

            Articulos art = articulos.get(indiceActual);
            setTextos(art, indiceActual, totalResultados);
            mostrarTabla();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e);

        }

        return articulos;
    }
    public ArrayList getArticulosnombresPrecios() {

        try {

            String sql = "select * from Articulos";

            PreparedStatement pstm = cone.prepareStatement(sql);
            ResultSet resultados = pstm.executeQuery();

            while (resultados.next()) {
                
                String nombre = resultados.getString("Nombre");
                int precio = resultados.getInt("precio") - 10;
                
                Articulos articulo = new Articulos(nombre, precio);

                articulos.add(articulo);
            }

            Articulos art = articulos.get(indiceActual);
            setTextos(art, indiceActual, totalResultados);
            mostrarTabla();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e);

        }

        return articulos;
    }

    public ArrayList getArticulosPreciocambiado() {

        try {

            String sql = "select * from Articulos where precio >= 450";

            PreparedStatement pstm = cone.prepareStatement(sql);
            ResultSet resultados = pstm.executeQuery();

            while (resultados.next()) {
                String claveArticulo = resultados.getString("claveArticulo");
                String nombre = resultados.getString("Nombre");
                int precio = resultados.getInt("precio") - 10;
                String claveFabricante = resultados.getString("claveFabricante");
                String nombreFabricante = resultados.getString("nombreFabricante");
                Articulos articulo = new Articulos(claveArticulo, nombre, precio, claveFabricante, nombreFabricante);

                articulos.add(articulo);
            }

            Articulos art = articulos.get(indiceActual);
            setTextos(art, indiceActual, totalResultados);
            mostrarTabla();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e);

        }

        return articulos;
    }

    public void setTextos(Articulos art, int indiceActual, int totalResultados) {

        txtClaveproducto.setText(art.getClaveArticulo());
        txtNombre.setText(art.getNombre());
        txtPrecio.setText(String.valueOf(art.getPrecio()));
        txtClaveFabricante.setText(art.getClaveFabricante());
        txtNombrefabricante.setText(art.getNombreFabricante());

        txtAnterior.setText(String.valueOf(indiceActual + 1));
        txtSiguiente.setText(String.valueOf(totalResultados));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaArt;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnDescuentp;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAnterior;
    private javax.swing.JTextField txtClaveFabricante;
    private javax.swing.JTextField txtClaveproducto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombrefabricante;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSiguiente;
    // End of variables declaration//GEN-END:variables
}
